#!/usr/bin/env python3
"""Project the intake specs into paste-ready Claude Project bundles.

A stakeholder can't run a vault agent directly, so for the team test we project
the coach and reviewer specs onto a surface they can use self-serve: a Claude
Project each. This script assembles two self-contained bundles from the
canonical specs — author once in the vault, project here — so the Projects never
drift from the source. Re-run after editing any source spec, then re-paste.

Outputs (generated — do not hand-edit):
  design-brain/projects/brief-coach-project.md
  design-brain/projects/brief-reviewer-project.md
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "design-brain" / "projects"

CONTRACT = ROOT / "design-brain" / "brief-contract.md"
COACH = ROOT / "design-brain" / "agents" / "brief-coach.md"
REVIEWER = ROOT / "design-brain" / "agents" / "brief-reviewer.md"
TEMPLATE = ROOT / "discovery" / "briefs" / "_TEMPLATE.md"

FRONT = """---
type: tool-projection
status: draft
owner: design-system
surfaces: [shared]
source: code
last_reviewed: 2026-07-21
maturity_score: 0
tags: [orbit, design-brain, intake, brief, projection]
---
"""

GEN_NOTE = ("<!-- generated by tools/build_project_bundles.py from the vault specs — "
            "do not hand-edit; re-run and re-paste after changing the source. -->")


def body(path: Path) -> str:
    """Return a spec's body: top frontmatter and the graph footer stripped."""
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"^---\n.*?\n---\n", "", text, count=1, flags=re.S)
    text = re.sub(r"\n*<!-- graph-links:start.*?<!-- graph-links:end -->\n?", "\n",
                  text, flags=re.S)
    return text.strip()


COACH_WRAP = """# Orbit Brief Coach — Claude Project bundle

**Owner setup:** create a new Claude Project named *Orbit Brief Coach*, and paste
everything below (from "Your role" down) into its custom instructions — or add this file
to the Project's knowledge. Share the Project with your testers; each tester just starts a
normal chat.

**The firewall:** this Project **only coaches**. It never judges a brief, never says a
brief will pass. Judging happens in a **separate** *Orbit Brief Reviewer* Project. Never do
both in the same chat — that's what keeps the gate honest.

**Open every new chat with this message:**
> Hi — I'll help you turn a rough idea into a sharp concept brief for the design team, just
> by asking a few questions. Nothing to prepare. In a sentence or two: what's the thing you
> want to build or fix?

Then follow the spec exactly.

---

## Your role — coach spec

"""

REVIEWER_WRAP = """# Orbit Brief Reviewer — Claude Project bundle

**Owner setup:** create a new Claude Project named *Orbit Brief Reviewer*, and paste
everything below (from "Your role" down) into its custom instructions. **Optionally** add
the platform profiles (`design-brain/platforms/*.md`) to the Project's knowledge so
criterion 8 can be checked against real profiles. Keep this **separate** from the coach
Project.

**How testers use it:** paste a submitted brief; the reviewer returns the verdict in the
fixed format. If the platform/surface can't be verified from what's provided, it says so
under criterion 8 — it must not invent context.

---

## Your role — reviewer spec

"""


def build() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    contract = body(CONTRACT)
    template = body(TEMPLATE)

    coach = (
        FRONT + GEN_NOTE + "\n\n" + COACH_WRAP + body(COACH)
        + "\n\n---\n\n## The standard you coach toward\n\n"
        + "_Your private checklist — the eight criteria. Do not read it out; use it to know "
        + "what a strong brief needs._\n\n" + contract
        + "\n\n---\n\n## The brief shape to play back\n\n"
        + "_When you play the brief back, use this structure._\n\n" + template + "\n"
    )
    reviewer = (
        FRONT + GEN_NOTE + "\n\n" + REVIEWER_WRAP + body(REVIEWER)
        + "\n\n---\n\n## The standard you score against\n\n" + contract + "\n"
    )

    (OUT / "brief-coach-project.md").write_text(coach, encoding="utf-8")
    (OUT / "brief-reviewer-project.md").write_text(reviewer, encoding="utf-8")
    print("Wrote:")
    print("  design-brain/projects/brief-coach-project.md")
    print("  design-brain/projects/brief-reviewer-project.md")


if __name__ == "__main__":
    build()
