#!/usr/bin/env python3
"""Generate the Obsidian graph layer for the Orbit Design Brain.

The vault's canonical cross-references are back-ticked plain paths
(agent/export-friendly), which Obsidian's graph view cannot see. This script
derives real wikilinks from those references and maintains a marked footer
block per document:

    <!-- graph-links:start ... -->
    ## Vault graph
    [[design-brain/tokens|tokens]] · ...
    <!-- graph-links:end -->

Rules:
- The back-ticked references stay canonical; the footer is a generated view.
  Never hand-edit it — re-run this script after adding/removing references.
- Wikilinks always use the full vault path (the vault has duplicate basenames:
  README, _TEMPLATE, SKILL, manifest), aliased to a short readable name.
- Only references that resolve to a real vault file are linked (resolution
  reuses tools/check_links.py). Self-references and non-.md targets are
  dropped: the graph is for navigating notes, and Obsidian only previews
  markdown.
- Files with no resolvable references get no footer.
- ``--check`` exits 1 if regeneration would change any file (CI guard).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_links import (  # noqa: E402
    EXTERNAL_BASENAMES,
    EXTERNAL_PREFIXES,
    REF_PATTERN,
    ROOT,
    WELL_KNOWN_DIRS,
    iter_docs,
)

START = "<!-- graph-links:start — generated by tools/gen_graph_links.py; do not hand-edit -->"
END = "<!-- graph-links:end -->"
BLOCK_RE = re.compile(
    r"\n*<!-- graph-links:start[^\n]*-->\n.*?<!-- graph-links:end -->\n?",
    re.DOTALL,
)


def resolve_to_path(ref: str, doc: Path) -> Path | None:
    """Resolve a back-ticked reference to a real vault file, or None.

    Mirrors check_links.resolves(), but returns the winning path because the
    wikilink needs it. External references resolve to None (not linkable).
    """
    if ref.startswith(EXTERNAL_PREFIXES):
        return None
    if "/" not in ref and ref in EXTERNAL_BASENAMES and ref not in {"AGENTS.md", "CLAUDE.md"}:
        return None  # product-repo files; AGENTS/CLAUDE are real vault roots

    candidates = [ROOT / ref, doc.parent / ref, ROOT / "design-brain" / ref]
    if ref.startswith("design-brain/_benchmarks/"):
        candidates.append(ROOT / ref.replace("design-brain/_benchmarks/", "_benchmarks/", 1))
    if "/" not in ref:
        candidates.extend(ROOT / d / ref for d in WELL_KNOWN_DIRS)
    for c in candidates:
        if c.is_file():
            return c
    return None


def graph_targets(doc: Path, text: str) -> list[Path]:
    seen: dict[Path, None] = {}
    for match in REF_PATTERN.finditer(text):
        target = resolve_to_path(match.group(1), doc)
        if target is None or target.suffix != ".md" or target == doc:
            continue
        seen.setdefault(target.resolve(), None)
    return sorted(seen, key=lambda p: p.relative_to(ROOT).as_posix())


def wikilink(target: Path) -> str:
    rel = target.relative_to(ROOT).as_posix()
    path_no_ext = rel[: -len(".md")]
    alias = target.stem
    if alias in {"README", "_TEMPLATE", "SKILL", "manifest", "INBOX"}:
        alias = f"{target.parent.name} {alias}"
    return f"[[{path_no_ext}|{alias}]]"


def render_block(targets: list[Path]) -> str:
    links = " · ".join(wikilink(t) for t in targets)
    return f"\n{START}\n## Vault graph\n{links}\n{END}\n"


def regenerate(doc: Path) -> tuple[str, str]:
    """Return (current_text, desired_text) for a doc."""
    text = doc.read_text(encoding="utf-8")
    stripped = BLOCK_RE.sub("\n", text).rstrip("\n") + "\n"
    targets = graph_targets(doc, stripped)
    desired = stripped + render_block(targets) if targets else stripped
    return text, desired


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if regeneration would change any file")
    args = parser.parse_args()

    changed: list[str] = []
    linked = 0
    for doc in iter_docs():
        current, desired = regenerate(doc)
        if START in desired:
            linked += 1
        if current != desired:
            changed.append(doc.relative_to(ROOT).as_posix())
            if not args.check:
                doc.write_text(desired, encoding="utf-8")

    if args.check:
        if changed:
            print(f"GRAPH LINKS STALE ({len(changed)} file(s)):")
            for rel in changed:
                print(f"- {rel}")
            print("Re-run: python3 tools/gen_graph_links.py")
            raise SystemExit(1)
        print(f"Graph links current: {linked} docs carry a Vault graph block.")
        return

    print(f"Graph links: {len(changed)} file(s) updated, {linked} docs carry a block.")


if __name__ == "__main__":
    main()
