#!/usr/bin/env python3
"""Vault health check for the Orbit Design Brain.

Produces a single daily read on whether the vault is staying healthy as more
people read it and add context. It writes:

- ``HEALTH.md`` (vault root)      — full internal report; file paths allowed.
- ``vault-health.html`` (root)    — sanitized, self-contained page for
  stakeholders. Aggregate counts, status mix, trend, freshness — plus a
  drill-down of item *names* for the areas whose names are generic
  design-system vocabulary (agents, skills, components, patterns). Product
  areas (examples, platforms) stay counts-only, because their titles name real
  Efficio surfaces. **Never a repo file path.** Safe to publish.
- ``tools/health_history.json``   — one aggregate snapshot per day; the trend
  source and the basis for day-over-day deltas.

With ``--artifact-out PATH`` it also writes a body-only, *full* drill-down
version (every area including examples) for the private Claude Artifact the
owner shares deliberately.

It reuses ``lint_frontmatter``'s parser (which already strips the inline-YAML
comments that trip a naive reader) and its lintable-doc set, and shells out to
the existing gating tools to record integrity status (informational here — CI
still gates separately).

A ``DRIFT``/``HEALTHY`` verdict is printed and, with ``--json``, emitted as
machine-readable output for the CI alert step. Drift = any stale doc, any
malformed doc, any integrity check failing, or the in-review backlog growing
since the previous snapshot.

Regenerating on the same day replaces that day's snapshot, so the tool is
idempotent — a second run changes nothing but proves clean.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import subprocess
import sys
from collections import Counter
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lint_frontmatter as lf  # noqa: E402  (reuse parser + lintable set)

ROOT = lf.ROOT
HISTORY_PATH = ROOT / "tools" / "health_history.json"
HEALTH_MD = ROOT / "HEALTH.md"
HEALTH_HTML = ROOT / "vault-health.html"
# Hand-maintained index of Claude Artifacts (deliverables). Rendered only on the
# private/full dashboard — never the public page (titles name product surfaces).
ARTIFACTS_MANIFEST = ROOT / "tools" / "artifacts-manifest.json"
# Component-library CI status, generated by tools/fetch_storybook_status.py.
# Informational only — deliberately NOT part of INTEGRITY_CHECKS (see below).
STORYBOOK_STATUS = ROOT / "tools" / "storybook-status.json"
# How long a fetched status stays trustworthy. Past this the dashboard reports
# "unknown" rather than a green tick that is silently weeks old.
STORYBOOK_STALE_DAYS = 3

STALE_AFTER_DAYS = lf.STALE_AFTER_DAYS
HISTORY_CAP = 180

# The feedback loop's queue (AGENTS.md §6). Agents append corrections here mid-task;
# a human triages them into a brain file or an agent trap, then deletes the entry.
# Nothing reads this file at build time and triage is deliberately not wired to CI
# (design-brain/orchestration.md), so a stalled queue is invisible unless reported.
# That is what this counter is for — it does not automate triage, it just stops the
# backlog being silently indistinguishable from an empty one.
LESSONS_INBOX = ROOT / "design-brain" / "lessons" / "INBOX.md"
LESSON_ENTRY = re.compile(r"^### (\d{4}-\d{2}-\d{2})\s+·", re.M)
LESSON_STATUS = re.compile(r"^- Status:\s*(\S+)", re.M)
SKIP_PARTS = {"_archive", ".obsidian", ".git"}

# Areas keyed by frontmatter `type` (robust to file moves/renames).
CONTRACT_AREAS = {
    "Component contracts": "component-contract",
    "Pattern contracts": "pattern-contract",
    "Examples": "example",
    "Platform profiles": "platform-profile",
}
AREA_ORDER = ("Agents", "Skills", "Component contracts", "Pattern contracts",
              "Examples", "Platform profiles", "Total docs")
# Cards shown in the dashboard grid (Total is promoted into the hero line).
CARD_ORDER = ("Agents", "Skills", "Component contracts", "Pattern contracts",
              "Examples", "Platform profiles")

# Plain-language gloss per area, so a stakeholder who doesn't know the vault can
# still read the dashboard. Generic (safe for the public page).
#
# "Contract" is glossed deliberately: to a procurement audience the word means a
# commercial agreement, and it was the single biggest comprehension blocker in the
# 2026-07-29 fresh-eyes review. Renaming it across the vault is a governed
# vocabulary change; glossing it on first use is not.
AREA_GLOSS = {
    "Agents": "AI agents that build & review designs",
    "Skills": "Guided workflows the team runs",
    "Component contracts": "Written specs for reusable UI pieces (not commercial contracts)",
    "Pattern contracts": "Written specs for whole-page layouts",
    "Examples": "Golden reference screens to build from",
    "Platform profiles": "The products the vault serves",
}

# Owner attribution. The name is internal-only: the public page names the role, and
# tools/build_site.py carries the name in its BLOCKLIST so a leak fails the build.
OWNER_NAME = "Derek Wong"
OWNER_ROLE = "design-system"

# Contract slug -> the component name in packages/orbit/src that implements it.
# Needed because the two vocabularies differ (`dialog` is implemented by `Overlay`).
# A contract missing from this map counts as "no stories" and warns on stderr, so a
# new contract can never silently inflate coverage.
CONTRACT_COMPONENTS = {
    "data-table": "Table",
    "button": "Button",
    "input": "Input",
    "select-combobox": "Dropdown",
    "dialog": "Overlay",
    "drawer": None,               # no reusable source exists yet
    "toast-notification": "Toast",
    "tabs": "TabButton",
    "badge-status": "Badge",
    "card-panel": "Card",
    "status-indicator": "StatusIndicator",
    "chip": "Chip",
}

# Which areas may reveal their item names on the *public* page. Agents, skills,
# components and patterns are generic design-system vocabulary; examples and
# platform profiles name real product surfaces, so they stay counts-only.
PUBLIC_EXPANDABLE = {"Agents", "Skills", "Component contracts", "Pattern contracts"}
# The private Artifact may expand everything with items (never the Total).
PRIVATE_EXPANDABLE = PUBLIC_EXPANDABLE | {"Examples", "Platform profiles"}

# Plain-language names + one-liners for the technical integrity checks.
#
# SHARED SOURCE: this dict is written into tools/health_history.json (see
# snapshot()) and read by tools/build_about_page.py to render the About page's
# check list. Both pages previously hand-maintained their own names, which had
# already drifted ("Document metadata is valid" vs "frontmatter") — a reader
# comparing the two pages concluded there were eight checks. Rename here only.
CHECK_LABELS = {
    "export self-check": ("All required files present", "Nothing the system depends on is missing."),
    "link check": ("Every internal link works", "No broken references between documents."),
    "frontmatter lint": ("Document metadata is valid", "Every doc is tagged and dated correctly."),
    "graph links": ("Navigation index up to date", "The cross-links between docs are current."),
}

# What each maturity status means, in plain words (for the legend).
STATUS_MEANING = {
    "stable": "reviewed & approved",
    "in-review": "being worked on",
    "draft": "just started",
}

# Gating tools run for the integrity read-out (name -> argv).
#
# Every entry here is a LOCAL script whose exit code gates the healthy/needs-
# attention verdict, which in turn opens and closes a GitHub issue from the
# `health` job. Do not add the component repo's CI status: a flaky external
# build would mark *the vault* unhealthy and file a drift alert for something
# the vault cannot fix. Storybook status is rendered by
# _component_library_section() as informational, non-gating context instead.
INTEGRITY_CHECKS = {
    "export self-check": ["export_brain.py", "--self-check"],
    "link check": ["check_links.py"],
    "frontmatter lint": ["lint_frontmatter.py"],
    "graph links": ["gen_graph_links.py", "--check"],
}


# --------------------------------------------------------------------------- #
# Scanning
# --------------------------------------------------------------------------- #
GENERATED_OUTPUTS = {"HEALTH.md"}  # this tool's own artifacts — not vault content


def all_docs() -> list[Path]:
    """Every living markdown doc (excludes archive/obsidian/git and this tool's
    own generated outputs)."""
    docs = []
    for path in sorted(ROOT.rglob("*.md")):
        rel = path.relative_to(ROOT)
        if any(part in SKIP_PARTS for part in rel.parts):
            continue
        if rel.as_posix() in GENERATED_OUTPUTS:
            continue
        docs.append(path)
    return docs


def _first_heading(path: Path) -> str | None:
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


_SENTENCE_END = re.compile(r"(?<=[.!?])\s")

# Section headings that introduce a document's own summary, best first. Contracts
# use `## Purpose`; golden examples use `## Demonstrates` (a bullet list).
_SUMMARY_SECTIONS = ("purpose", "demonstrates", "purpose & precedent", "what it is")


def _blocks(lines: list[str]) -> list[tuple[str, str]]:
    """(section, text) for each paragraph/bullet, with hard-wrapped lines joined.

    Markdown in this vault is hard-wrapped at ~90 columns, so a single source
    line is usually half a sentence. Reading one line at a time is what produced
    drawer descriptions like "rows." and "…access to underlying".
    """
    out: list[tuple[str, str]] = []
    section, buf, in_fm, fences = "", [], False, 0

    def flush() -> None:
        if buf:
            out.append((section, " ".join(buf).strip()))
            buf.clear()

    for i, raw in enumerate(lines):
        line = raw.rstrip()
        stripped = line.strip()
        if i == 0 and stripped == "---":
            in_fm = True
            continue
        if in_fm:
            in_fm = stripped != "---"
            continue
        if stripped.startswith("```"):
            fences += 1
            flush()
            continue
        if fences % 2:
            continue
        if stripped.startswith("#"):
            flush()
            if stripped.startswith("## "):
                section = stripped[3:].strip().lower()
            continue
        if not stripped or stripped.startswith(("|", ">", "<!--", "---")):
            flush()
            continue
        if stripped.startswith(("- ", "* ", "+ ")) or re.match(r"^\d+\.\s", stripped):
            flush()
            buf.append(re.sub(r"^([-*+]\s|\d+\.\s)", "", stripped))
            continue
        buf.append(stripped)
    flush()
    return out


def _looks_like_prose(s: str) -> bool:
    """True only for something a reader would accept as a written sentence.

    Golden examples embed screenshot links and repo paths; letting those through
    put strings like `foo.png(screenshots/connected-platform/foo.png)` in front of
    readers on a page whose whole subject is documentation quality. When nothing
    qualifies, `_doc_summary` returns "" and the drawer shows the name alone —
    no description is strictly better than a broken one.
    """
    if len(s) < 30 or "](" in s or "|" in s:
        return False
    if re.search(r"\.(png|jpe?g|svg|md|tsx?|css|json|py|html|canvas|base)\b", s):
        return False
    if s.count("/") >= 2:  # a repo path; single slashes ("semantic/status") are fine
        return False
    return s[:1].isupper() and s.rstrip().endswith((".", "!", "?"))


def _doc_summary(path: Path, fm: dict | None) -> str:
    """One plain sentence describing a document, for the private drawer lists.

    A drawer that lists 12 slugs and nothing else tells a reader what exists but
    not what any of it is. Preference order, most-authored first: frontmatter
    `description` (agents and skills carry one) -> the first qualifying block
    under a summary heading -> the first qualifying block anywhere.

    Private pages only — a description can name a product surface, and the
    public build must not carry those. `_panel_src` gates on `public`.
    """
    def sentence(s: str) -> str:
        """Markup stripped, first sentence only — full length, so the prose test
        sees a real sentence. Shortening happens after it passes, never before:
        an ellipsis ending would fail `_looks_like_prose` on its own output."""
        s = re.sub(r"[`*_]", "", str(s)).strip()
        s = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", s)  # [text](url) -> text
        return _SENTENCE_END.split(s, 1)[0].strip()

    def shorten(s: str) -> str:
        # Generous: these wrap freely in the drawer, and a sentence cut mid-clause
        # with no way to expand is worse than a long one.
        return s if len(s) <= 220 else s[:217].rsplit(" ", 1)[0] + "…"

    described = (fm or {}).get("description")
    if described:
        return shorten(sentence(described))

    blocks = _blocks(path.read_text(encoding="utf-8", errors="ignore").splitlines())
    ordered = [(s, t) for w in _SUMMARY_SECTIONS for s, t in blocks if s == w] + blocks
    for _, text in ordered:
        candidate = sentence(text)
        if _looks_like_prose(candidate):
            return shorten(candidate)
    return ""


def _example_name(path: Path) -> str:
    heading = _first_heading(path) or path.stem
    for prefix in ("Golden Example: ", "Golden Example — "):
        if heading.startswith(prefix):
            return heading[len(prefix):]
    return heading


def build_inventory(docs: list[Path]) -> dict[str, list[dict]]:
    """area -> [{name, status, desc}] sorted, for the drill-down.

    `desc` is rendered on the private dashboard only (see `_doc_summary`).
    """
    traps = agent_traps()
    by_type: dict[str, list[Path]] = {}
    for path in docs:
        fm = lf.parse_frontmatter(path)
        if fm and fm.get("type"):
            by_type.setdefault(fm["type"], []).append(path)

    def items(paths: list[Path], namer) -> list[dict]:
        out = []
        for p in paths:
            fm = lf.parse_frontmatter(p) or {}
            out.append({"name": namer(p), "status": fm.get("status"),
                        "desc": _doc_summary(p, fm)})
        return sorted(out, key=lambda d: d["name"].lower())

    agents = sorted((ROOT / "design-brain" / "agents").glob("*.md"))
    skills = sorted((ROOT / "design-brain" / "skills").glob("*/SKILL.md"))
    inv: dict[str, list[dict]] = {
        # Agent rows carry their trap/evidence counts so the private drawer can
        # show which agents have accumulated failure knowledge and which haven't.
        "Agents": [{**it, "traps": traps.get(it["name"])}
                   for it in items(agents, lambda p: p.stem)],
        "Skills": [
            {"name": (fm := lf.parse_frontmatter(p) or {}).get("name", p.parent.name),
             "status": None,
             "desc": _doc_summary(p, fm)}
            for p in skills
        ],
        "Component contracts": items(by_type.get("component-contract", []), lambda p: p.stem),
        "Pattern contracts": items(by_type.get("pattern-contract", []), lambda p: p.stem),
        "Examples": items(by_type.get("example", []), _example_name),
        "Platform profiles": items(by_type.get("platform-profile", []), lambda p: p.stem),
    }
    inv["Skills"].sort(key=lambda d: d["name"].lower())
    return inv


# The six inventory cards cover the reusable building blocks; the rest of the
# vault is rules, reviews, benchmark records and indexes. Buckets are matched on
# frontmatter `type` so the split is computed, never hand-counted — a reader who
# subtracts 59 from 142 must find the remainder accounted for, not unexplained.
REST_BUCKETS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("benchmark records", ("benchmark",)),
    ("rules and foundations",
     ("foundation", "principle", "token-contract", "tooling-guide", "orchestration",
      "setup-guide", "governance", "visual-truth")),
    ("reviews and proposals", ("review", "proposal", "lessons-inbox")),
    ("discovery and concept briefs", ("discovery", "concept-brief")),
)


def rest_of_vault(docs: list[Path], inventory: dict[str, list[dict]]) -> dict:
    """Account for every document the six inventory cards do not list."""
    counted = sum(len(v) for v in inventory.values())
    buckets: dict[str, int] = {label: 0 for label, _ in REST_BUCKETS}
    other = 0
    listed_types = {"example", "component-contract", "pattern-contract",
                    "platform-profile", "builder-agent", "reviewer-agent",
                    "coach-agent", "orchestration-agent", "maintenance-agent"}
    for path in docs:
        fm = lf.parse_frontmatter(path) or {}
        t = fm.get("type") or ""
        if t in listed_types or path.name == "SKILL.md":
            continue
        for label, prefixes in REST_BUCKETS:
            if t.startswith(prefixes):
                buckets[label] += 1
                break
        else:
            other += 1
    return {"listed": counted, "buckets": buckets, "other": other,
            "total": counted + sum(buckets.values()) + other}


AGENTS_DIR = ROOT / "design-brain" / "agents"
BENCHMARK_RESULTS = ROOT / "_benchmarks" / "results"
TRAPS_HEADING = re.compile(r"^## .*\btraps\b.*$", re.I | re.M)
TRAP_BULLET = re.compile(r"^- ", re.M)
CITED_FILE = re.compile(r"`([^`]+\.md)`")


def agent_traps() -> dict[str, dict]:
    """Per-agent trap count and evidence base, keyed by agent stem.

    `runs` counts citations that resolve to a file in `_benchmarks/results/` —
    a scored run. `sources` counts every distinct cited file, which includes
    doctrine files and dated incident records. The distinction matters: a trap
    citing a scorecard is stronger evidence than one citing a rule, and today
    most traps are the latter.
    """
    results = {p.name for p in BENCHMARK_RESULTS.glob("*.md")} \
        if BENCHMARK_RESULTS.is_dir() else set()
    out: dict[str, dict] = {}
    for path in sorted(AGENTS_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        head = TRAPS_HEADING.search(text)
        if not head:
            out[path.stem] = {"traps": 0, "sources": 0, "runs": 0}
            continue
        rest = text[head.end():]
        nxt = re.search(r"^## ", rest, re.M)
        section = rest[: nxt.start()] if nxt else rest
        cited = {Path(c).name for c in CITED_FILE.findall(section)}
        out[path.stem] = {
            "traps": len(TRAP_BULLET.findall(section)),
            "sources": len(cited),
            "runs": len(cited & results),
        }
    return out


def trap_coverage() -> dict:
    """How much recorded evidence the agents' traps actually rest on.

    Traps are inline failure modes on an agent, each citing the benchmark result
    or correction that produced it (`design-brain/orchestration.md`). They are
    only as good as that evidence, so this reports the base rather than implying
    the traps are finished: how many agents carry any, how many recorded results
    exist, and how many of those have never been cited by a trap. The last number
    is the actionable one — it is unmined evidence, not a defect.
    """
    agents = sorted(AGENTS_DIR.glob("*.md"))
    traps = 0
    with_traps = 0
    cited: set[str] = set()
    for path in agents:
        text = path.read_text(encoding="utf-8", errors="ignore")
        head = TRAPS_HEADING.search(text)
        if not head:
            continue
        rest = text[head.end():]
        nxt = re.search(r"^## ", rest, re.M)
        section = rest[: nxt.start()] if nxt else rest
        n = len(TRAP_BULLET.findall(section))
        if not n:
            continue
        with_traps += 1
        traps += n
        cited.update(Path(c).name for c in CITED_FILE.findall(section))
    results = sorted(p.name for p in BENCHMARK_RESULTS.glob("*.md")) \
        if BENCHMARK_RESULTS.is_dir() else []
    return {
        "agents": len(agents),
        "with_traps": with_traps,
        "traps": traps,
        "sources": len(cited),
        "results": len(results),
        "unmined": len([r for r in results if r not in cited]),
    }


def open_lessons(today: date) -> list[str]:
    """Inbox entries whose fix has not landed yet, oldest first.

    An entry is open unless its Status line starts with `applied`. The template
    block inside the file is skipped: it documents the shape, not a real entry.
    Returns [] when the file is missing — the counter reports zero rather than
    breaking the whole report over a missing optional input.
    """
    if not LESSONS_INBOX.is_file():
        return []
    text = LESSONS_INBOX.read_text(encoding="utf-8", errors="ignore")
    body = text.split("## Entries", 1)[-1]
    out: list[str] = []
    for match in LESSON_ENTRY.finditer(body):
        entry = body[match.start():]
        nxt = LESSON_ENTRY.search(entry[1:])
        if nxt:
            entry = entry[: nxt.start() + 1]
        status = LESSON_STATUS.search(entry)
        if status and status.group(1).lower().startswith("applied"):
            continue
        raised = match.group(1)
        try:
            age = (today - date.fromisoformat(raised)).days
        except ValueError:
            age = 0
        out.append(f"{raised}  ({age}d open)")
    return sorted(out)


def scan(today: date) -> dict:
    docs = all_docs()
    inventory = build_inventory(docs)

    areas = {label: len(inventory[label]) for label in inventory}
    areas["Total docs"] = len(docs)
    rest = rest_of_vault(docs, inventory)

    # Status mix over docs that carry a status field (skill files legitimately
    # do not — they use the Claude-skill frontmatter shape).
    status = Counter()
    for path in docs:
        fm = lf.parse_frontmatter(path)
        if fm and "status" in fm:
            status[fm["status"]] += 1

    # Attention: stale (>90d) and malformed, over the canonical governed set
    # that CI lints — lf.iter_targets() already exempts skills, templates,
    # manifests, and benchmark results, so this matches what CI enforces.
    cutoff = today - timedelta(days=STALE_AFTER_DAYS)
    stale: list[str] = []
    malformed: list[str] = []
    for path in lf.iter_targets():
        rel = path.relative_to(ROOT).as_posix()
        fm = lf.parse_frontmatter(path)
        if fm is None:
            malformed.append(f"{rel} — no frontmatter block")
            continue
        st = fm.get("status")
        if st is None:
            malformed.append(f"{rel} — missing status")
        elif st not in lf.VALID_STATUS:
            malformed.append(f"{rel} — invalid status '{st}'")
        reviewed = fm.get("last_reviewed")
        if reviewed:
            try:
                if date.fromisoformat(reviewed) < cutoff:
                    stale.append(f"{reviewed}  {rel}")
            except ValueError:
                malformed.append(f"{rel} — last_reviewed '{reviewed}' not YYYY-MM-DD")

    integrity = run_integrity()

    return {
        "date": today.isoformat(),
        "areas": areas,
        "inventory": inventory,
        "status": {k: status.get(k, 0) for k in ("stable", "in-review", "draft")},
        "status_total": sum(status.values()),
        "stale": sorted(stale),
        "malformed": sorted(malformed),
        "integrity": integrity,
        "rest": rest,
        "lessons": open_lessons(today),
        "traps": trap_coverage(),
    }


def run_integrity() -> dict[str, bool]:
    results: dict[str, bool] = {}
    for name, argv in INTEGRITY_CHECKS.items():
        try:
            proc = subprocess.run(
                [sys.executable, str(ROOT / "tools" / argv[0]), *argv[1:]],
                cwd=ROOT, capture_output=True, text=True, timeout=300,
            )
            results[name] = proc.returncode == 0
        except Exception:  # a check that cannot run is a failed check
            results[name] = False
    return results


# --------------------------------------------------------------------------- #
# History + verdict
# --------------------------------------------------------------------------- #
def load_history() -> list[dict]:
    if not HISTORY_PATH.is_file():
        return []
    try:
        data = json.loads(HISTORY_PATH.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else []
    except json.JSONDecodeError:
        return []


def story_coverage(inventory: dict) -> dict | None:
    """Contracted-first story coverage.

    The headline "1 of 52" answers "how much of the library is storied"; the
    number the team can actually act on is "do the components we have already
    written contracts for have stories?" — that is the near-term target. Returns
    None when the status feed is absent so callers can degrade quietly.
    """
    if not STORYBOOK_STATUS.is_file():
        return None
    try:
        d = json.loads(STORYBOOK_STATUS.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None

    storied = set(d.get("storied_components") or [])
    # build_inventory() yields [{name, status}, ...]; the name IS the contract slug.
    slugs = [it["name"] for it in inventory.get("Component contracts", [])]

    matched, unmapped = 0, []
    for slug in slugs:
        if slug not in CONTRACT_COMPONENTS:
            unmapped.append(slug)
            continue
        comp = CONTRACT_COMPONENTS[slug]
        if comp and comp in storied:
            matched += 1
    if unmapped:
        print(f"warning: contract slug(s) not in CONTRACT_COMPONENTS, counted as "
              f"no-stories: {', '.join(sorted(unmapped))}", file=sys.stderr)

    return {
        "contracts": len(slugs),
        "contracts_with_stories": matched,
        "components": d.get("components") or 0,
        "components_with_stories": d.get("components_with_stories") or 0,
        "story_files": d.get("story_files") or 0,
    }


def snapshot(scanned: dict) -> dict:
    snap = {
        "date": scanned["date"],
        "areas": scanned["areas"],
        "status": scanned["status"],
        "stale": len(scanned["stale"]),
        "malformed": len(scanned["malformed"]),
        "integrity_ok": all(scanned["integrity"].values()),
        # Shared vocabulary for build_about_page.py — one source for check names.
        "check_labels": {k: list(v) for k, v in CHECK_LABELS.items()},
    }
    cov = story_coverage(scanned.get("inventory", {}))
    if cov:
        # Recorded from today so the trend can plot coverage once ≥2 points exist.
        snap["coverage"] = cov
    return snap


def update_history(scanned: dict) -> tuple[list[dict], dict | None]:
    """Append/replace today's snapshot; return (history, previous_snapshot)."""
    history = [h for h in load_history() if h.get("date") != scanned["date"]]
    previous = history[-1] if history else None
    history.append(snapshot(scanned))
    history = history[-HISTORY_CAP:]
    HISTORY_PATH.write_text(
        json.dumps(history, indent=2) + "\n", encoding="utf-8"
    )
    return history, previous


def verdict(scanned: dict, previous: dict | None) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    if scanned["stale"]:
        reasons.append(f"{len(scanned['stale'])} doc(s) not reviewed in {STALE_AFTER_DAYS}+ days")
    if scanned["malformed"]:
        reasons.append(f"{len(scanned['malformed'])} doc(s) with malformed frontmatter")
    failed = [n for n, ok in scanned["integrity"].items() if not ok]
    if failed:
        reasons.append("integrity check failed: " + ", ".join(failed))
    if previous is not None:
        grew = scanned["status"]["in-review"] - previous["status"]["in-review"]
        if grew > 0:
            reasons.append(f"in-review backlog grew by {grew} since {previous['date']}")
    return (not reasons), reasons


# --------------------------------------------------------------------------- #
# Markdown report (internal — file paths allowed)
# --------------------------------------------------------------------------- #
def _delta(cur: int, prev: int | None) -> str:
    if prev is None or cur == prev:
        return ""
    return f" ({'+' if cur > prev else ''}{cur - prev})"


def render_md(scanned: dict, previous: dict | None, healthy: bool, reasons: list[str]) -> str:
    a = scanned["areas"]
    s = scanned["status"]
    pa = previous["areas"] if previous else {}
    ps = previous["status"] if previous else {}
    lines = [
        "<!-- generated by tools/vault_health.py — do not hand-edit; run the tool to refresh -->",
        "# Vault Health",
        "",
        f"_Snapshot {scanned['date']}. Regenerate with `tools/vault_health.py`._",
        "",
        f"**Status: {'HEALTHY ✅' if healthy else 'NEEDS ATTENTION ⚠️'}**",
    ]
    if reasons:
        lines += [""] + [f"- {r}" for r in reasons]
    lines += ["", "## Contents", "", "| Area | Count |", "| --- | ---: |"]
    for label in AREA_ORDER:
        lines.append(f"| {label} | {a[label]}{_delta(a[label], pa.get(label))} |")

    total = scanned["status_total"] or 1
    lines += ["", "## Status mix", "",
              f"_{scanned['status_total']} docs carry a status field "
              "(skill files use a different frontmatter shape and are exempt)._",
              "", "| Status | Count | Share |", "| --- | ---: | ---: |"]
    for key in ("stable", "in-review", "draft"):
        pct = round(100 * s[key] / total)
        lines.append(f"| {key} | {s[key]}{_delta(s[key], ps.get(key))} | {pct}% |")

    lines += ["", "## Inventory", ""]
    for label in ("Agents", "Skills", "Component contracts", "Pattern contracts",
                  "Examples", "Platform profiles"):
        items = scanned["inventory"][label]
        lines.append(f"### {label} ({len(items)})")
        for it in items:
            tag = f" — {it['status']}" if it["status"] else ""
            lines.append(f"- {it['name']}{tag}")
        lines.append("")

    lines += ["## Integrity checks", "", "| Check | Result |", "| --- | --- |"]
    for name, ok in scanned["integrity"].items():
        lines.append(f"| {name} | {'pass ✅' if ok else 'FAIL ❌'} |")

    lines += ["", "## Freshness", "",
              f"- Stale (>{STALE_AFTER_DAYS}d since review): **{len(scanned['stale'])}**"]
    for item in scanned["stale"]:
        lines.append(f"  - {item}")
    lines += [f"- Malformed frontmatter: **{len(scanned['malformed'])}**"]
    for item in scanned["malformed"]:
        lines.append(f"  - {item}")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# HTML (shared body; wrapped standalone for Pages, body-only for the Artifact)
# --------------------------------------------------------------------------- #
STYLE = """
  :root{
    --bg:#f5f7fa;--panel:#fff;--panel-2:#f0f3f8;--ink:#141922;--muted:#59626f;
    --line:#e4e9f0;--accent:#0e7c86;--stable:#1f9d55;--review:#c98a00;
    --draft:#64748b;--warn:#c2410c;--track:#eaeef4;
    --shadow:0 1px 2px rgba(20,25,34,.04),0 8px 24px rgba(20,25,34,.05);
  }
  @media (prefers-color-scheme:dark){:root{
    --bg:#0c0f14;--panel:#141922;--panel-2:#0f141b;--ink:#e9edf3;--muted:#98a2b2;
    --line:#232a35;--accent:#2dd4bf;--stable:#3ecf7f;--review:#e5b84b;
    --draft:#94a3b8;--warn:#f0894e;--track:#1c232e;
    --shadow:0 1px 2px rgba(0,0,0,.3),0 10px 30px rgba(0,0,0,.35);}}
  :root[data-theme=light]{
    --bg:#f5f7fa;--panel:#fff;--panel-2:#f0f3f8;--ink:#141922;--muted:#59626f;
    --line:#e4e9f0;--accent:#0e7c86;--stable:#1f9d55;--review:#c98a00;
    --draft:#64748b;--warn:#c2410c;--track:#eaeef4;
    --shadow:0 1px 2px rgba(20,25,34,.04),0 8px 24px rgba(20,25,34,.05);}
  :root[data-theme=dark]{
    --bg:#0c0f14;--panel:#141922;--panel-2:#0f141b;--ink:#e9edf3;--muted:#98a2b2;
    --line:#232a35;--accent:#2dd4bf;--stable:#3ecf7f;--review:#e5b84b;
    --draft:#94a3b8;--warn:#f0894e;--track:#1c232e;
    --shadow:0 1px 2px rgba(0,0,0,.3),0 10px 30px rgba(0,0,0,.35);}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    line-height:1.5;-webkit-font-smoothing:antialiased}
  .mono{font-family:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
    font-variant-numeric:tabular-nums}
  .wrap{max-width:900px;margin:0 auto;padding:40px 22px 64px}
  .eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;
    color:var(--muted);font-weight:600}
  header{margin-bottom:26px}
  h1{font-size:23px;letter-spacing:-.01em;margin:6px 0 0;font-weight:650}
  .banner{margin-top:20px;display:flex;align-items:center;gap:18px;flex-wrap:wrap;
    background:var(--panel);border:1px solid var(--line);border-left:4px solid var(--verdict);
    border-radius:14px;padding:18px 22px;box-shadow:var(--shadow)}
  .dot{width:11px;height:11px;border-radius:50%;background:var(--verdict);
    box-shadow:0 0 0 4px color-mix(in srgb,var(--verdict) 22%,transparent);flex:none}
  .banner .verdict{font-size:17px;font-weight:650}
  .banner .meta{color:var(--muted);font-size:13px;margin-left:auto;text-align:right}
  .banner .summary-line{color:var(--muted);font-size:13.5px;margin-top:3px;
    font-variant-numeric:tabular-nums}
  section{margin-top:34px}
  .s-head{margin:0 0 4px;font-size:16px;font-weight:650;letter-spacing:-.01em}
  .s-sub{margin:0 0 16px;color:var(--muted);font-size:13px}
  .kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
  .kpi,.kpi-btn{background:var(--panel);border:1px solid var(--line);border-radius:14px;
    box-shadow:var(--shadow);display:flex;flex-direction:column;padding:17px 17px 18px}
  .kpi .n,.kpi-btn .n{font-size:29px;font-weight:650;letter-spacing:-.02em;line-height:1}
  .kpi .k,.kpi-btn .k{font-size:14px;font-weight:650;margin-top:9px}
  .gloss{font-size:12px;color:var(--muted);margin-top:4px;line-height:1.4}
  /* Expandable cards are buttons that open the slide-in drawer. */
  .kpi-btn{cursor:pointer;text-align:left;font:inherit;color:inherit;width:100%;
    transition:border-color .12s ease,transform .12s ease}
  .kpi-btn:hover{border-color:var(--accent);transform:translateY(-1px)}
  .kpi-btn:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
  .expand-hint{margin-top:12px;font-size:12px;font-weight:650;color:var(--accent);
    display:flex;align-items:center;gap:6px}
  .expand-hint .chev{font-size:14px;line-height:1}
  .pill{font-size:11px;padding:2px 8px;border-radius:999px;flex:none;font-weight:600;
    letter-spacing:.02em}
  /* Ink is darkened for light mode: these hues are tuned as fills and miss AA as
     text on their own tint (2.5-3.9:1). Fills and hues are unchanged. */
  .s-stable{color:color-mix(in srgb,var(--stable) 58%,#000);background:color-mix(in srgb,var(--stable) 14%,transparent)}
  .s-review{color:color-mix(in srgb,var(--review) 62%,#000);background:color-mix(in srgb,var(--review) 16%,transparent)}
  .s-draft{color:color-mix(in srgb,var(--draft) 70%,#000);background:color-mix(in srgb,var(--draft) 16%,transparent)}
  @media (prefers-color-scheme:dark){
    .s-stable{color:var(--stable)} .s-review{color:var(--review)} .s-draft{color:var(--draft)}}
  :root[data-theme=dark] .s-stable{color:var(--stable)}
  :root[data-theme=dark] .s-review{color:var(--review)}
  :root[data-theme=dark] .s-draft{color:var(--draft)}
  /* Side panel: docked right, slides in from the right, pushes content left —
     no overlay, no scrim. --dw is the panel width (full-width on small screens). */
  :root{--dw:400px}
  html{overflow-x:hidden}
  #shell{transition:margin-right .28s cubic-bezier(.4,0,.2,1)}
  body.drawer-open #shell{margin-right:var(--dw)}
  .drawer{position:fixed;top:0;right:0;height:100dvh;width:var(--dw);
    background:var(--panel);border-left:1px solid var(--line);
    box-shadow:-14px 0 34px rgba(10,14,20,.12);
    transform:translateX(100%);visibility:hidden;z-index:30;display:flex;flex-direction:column;
    transition:transform .28s cubic-bezier(.4,0,.2,1),visibility 0s linear .28s}
  body.drawer-open .drawer{transform:translateX(0);visibility:visible;
    transition:transform .28s cubic-bezier(.4,0,.2,1)}
  @media (max-width:820px){:root{--dw:100vw}
    body.drawer-open #shell{margin-right:0}}
  .drawer .dhead{display:flex;align-items:center;gap:10px;padding:20px 20px 15px;
    border-bottom:1px solid var(--line)}
  .drawer .dhead h3{margin:0;font-size:15px;font-weight:650}
  .drawer .dcount{font-size:12px;font-weight:650;color:var(--accent);
    background:color-mix(in srgb,var(--accent) 12%,transparent);border-radius:999px;padding:2px 9px}
  .drawer-close{margin-left:auto;background:none;border:1px solid var(--line);border-radius:8px;
    width:30px;height:30px;cursor:pointer;color:var(--muted);font-size:18px;line-height:1;
    display:grid;place-items:center}
  .drawer-close:hover{border-color:var(--accent);color:var(--ink)}
  .drawer-close:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
  .drawer .dgloss{padding:14px 20px 0;color:var(--muted);font-size:12.5px}
  .drawer-body{padding:10px 20px 24px;overflow:auto}
  .items{list-style:none;margin:0;padding:0}
  .items li{display:grid;grid-template-columns:1fr auto;align-items:center;gap:4px 10px;
    padding:10px 0;border-top:1px solid var(--line);font-size:13.5px}
  .items li:first-child{border-top:none}
  .items li .nm{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  /* One-line description under each drawer item — private dashboard only.
     A list of bare slugs says what exists but never what any of it is. */
  .items li .dsc{grid-column:1/-1;font-size:12px;color:var(--muted);line-height:1.45}
  /* Agent evidence base — private drawer only. */
  .items li .ev{grid-column:1/-1;font-size:10.5px;font-weight:650;letter-spacing:.02em;
    text-transform:uppercase;padding:2px 7px;border-radius:999px;justify-self:start;
    border:1px solid var(--line);color:var(--muted)}
  .items li .ev.ok{color:var(--stable);border-color:color-mix(in srgb,var(--stable) 40%,var(--line))}
  .items li .ev.thin{color:var(--warn);border-color:color-mix(in srgb,var(--warn) 40%,var(--line))}
  @media (prefers-reduced-motion:reduce){
    .kpi-btn,.kpi-btn:hover,#shell,.drawer{transition:none}
    body.drawer-open .drawer{transition:none}}
  .panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;
    padding:22px;box-shadow:var(--shadow)}
  .legend{display:flex;flex-wrap:wrap;gap:8px 18px;margin:0 0 16px;padding-bottom:16px;
    border-bottom:1px solid var(--line)}
  .legend .lg{display:flex;align-items:center;gap:7px;font-size:12.5px;color:var(--muted)}
  .legend .lg b{color:var(--ink);font-weight:600}
  .legend .sw{width:9px;height:9px;border-radius:2px;flex:none}
  .row{display:flex;align-items:center;gap:14px;padding:11px 0}
  .row+.row{border-top:1px solid var(--line)}
  .row .name{width:96px;font-size:13.5px;font-weight:550}
  .track{flex:1;height:9px;background:var(--track);border-radius:999px;overflow:hidden}
  .fill{display:block;height:100%;border-radius:999px}
  .row .val{width:104px;text-align:right;font-size:13.5px;color:var(--muted)}
  .row .val b{color:var(--ink);font-weight:600}
  .checks{display:grid;grid-template-columns:1fr 1fr;gap:10px 22px}
  .check{display:flex;align-items:flex-start;gap:10px;font-size:13.5px}
  .check .mk{flex:none;width:20px;height:20px;border-radius:50%;display:grid;place-items:center;
    font-size:12px;font-weight:700;margin-top:1px}
  .check.ok .mk{color:color-mix(in srgb,var(--stable) 60%,#000);background:color-mix(in srgb,var(--stable) 15%,transparent)}
  @media (prefers-color-scheme:dark){.check.ok .mk{color:var(--stable)}}
  :root[data-theme=dark] .check.ok .mk{color:var(--stable)}
  .check.bad .mk{color:var(--warn);background:color-mix(in srgb,var(--warn) 15%,transparent)}
  .check .ct{font-weight:600}
  .check .cd{display:block;color:var(--muted);font-size:12px;margin-top:1px}
  .fresh{display:flex;gap:16px;flex-wrap:wrap}
  .fresh .item{flex:1;min-width:150px;background:var(--panel-2);border:1px solid var(--line);
    border-radius:12px;padding:15px 16px;display:flex;align-items:center;gap:13px}
  .fresh .item .n{font-size:26px;font-weight:650}
  .fresh .item .k{font-size:13px;font-weight:600}
  .fresh .item .d{font-size:11.5px;color:var(--muted);margin-top:1px}
  .fresh .item.good .n{color:var(--stable)}
  /* A coverage figure short of target must NOT wear the success colour that
     "0 overdue" wears — the inverted colour language the 2026-07-29 review caught. */
  .fresh .item.warn{border-color:color-mix(in srgb,var(--warn) 45%,var(--line))}
  .fresh .item.warn .n{color:var(--warn)}
  .fresh .item .n .of{font-size:15px;font-weight:600;color:var(--muted)}
  /* Answers "what am I looking at?" before any number does. */
  .purpose{margin:10px 0 20px;font-size:14.5px;color:var(--muted);line-height:1.65;
    max-width:64ch}
  /* Public page: a card whose titles are withheld. Flat and chevron-less so it
     never reads as an expander that failed to open. */
  .kpi.inert{background:transparent;box-shadow:none;
    border-style:dashed;border-color:color-mix(in srgb,var(--line) 80%,transparent)}
  .kpi.inert .withheld{margin-top:8px;font-size:11px;color:var(--muted);font-style:italic}
  /* Reference prose, one click away. Collapsed it keeps ~190px of grey text from
     sitting between a phone reader and the first number; <details> needs no JS. */
  .explain{margin:14px 0 0}
  .explain>summary{cursor:pointer;font-size:12.5px;font-weight:650;color:var(--muted);
    list-style:none;display:inline-flex;align-items:center;gap:6px;padding:5px 0}
  .explain>summary::-webkit-details-marker{display:none}
  .explain>summary::before{content:"›";display:inline-block;transition:transform .18s ease;
    font-size:15px;line-height:1}
  .explain[open]>summary::before{transform:rotate(90deg)}
  .explain>summary:hover{color:var(--ink)}
  .explain>summary:focus-visible{outline:2px solid var(--accent);outline-offset:3px;
    border-radius:4px}
  @media (prefers-reduced-motion:reduce){.explain>summary::before{transition:none}}
  .verdict-def{margin:6px 0 0;font-size:12.5px;color:var(--muted);line-height:1.6}
  .denoms{margin:8px 0 0;font-size:12.5px;color:var(--muted);line-height:1.6}
  .verdict-def b,.denoms b{color:var(--ink);font-weight:650}
  .row .name .nm{display:block;font-size:11px;font-weight:500;color:var(--muted);margin-top:1px}
  .tr+.tr{margin-top:18px;padding-top:16px;border-top:1px solid var(--line)}
  .tl{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:6px}
  .tl .tk{font-size:13px;font-weight:650;display:flex;align-items:center;gap:8px}
  .tl .mv{font-size:10.5px;font-weight:650;text-transform:uppercase;letter-spacing:.04em;
    padding:2px 7px;border-radius:999px;border:1px solid var(--line);color:var(--muted)}
  .tl .mv.good{color:var(--stable);border-color:color-mix(in srgb,var(--stable) 40%,var(--line))}
  .tl .mv.warn{color:var(--warn);border-color:color-mix(in srgb,var(--warn) 40%,var(--line))}
  .tl .tv{font-size:12.5px;color:var(--muted);font-variant-numeric:tabular-nums}
  .tl .tv b{color:var(--ink);font-weight:650}
  .tl .ar{opacity:.6;padding:0 2px}
  .spark.k-stable path{stroke:var(--stable)}
  .spark.k-cov path{stroke:var(--accent)}
  .spark.k-docs path{stroke:var(--accent)}
  .spark{width:100%;height:56px}
  /* preserveAspectRatio="none" scales the viewBox ~11x horizontally and 1x
     vertically, which stretches the stroke itself — steep segments rendered as
     solid wedges rather than lines. non-scaling-stroke keeps it a 2px line. */
  .spark path{fill:none;stroke:var(--accent);stroke-width:2;
    vector-effect:non-scaling-stroke;stroke-linejoin:round;stroke-linecap:round}
  .cap{color:var(--muted);font-size:12.5px;margin:0}
  /* These were browser-default blue (#0000EE) — unstyled, and 1.87:1 on the dark
     panel. Scoped to .cap so the artifact rows, which carry their own treatment,
     are untouched. */
  .cap a{color:var(--accent);text-decoration:underline;text-underline-offset:2px;
    text-decoration-thickness:1px;font-weight:600}
  .cap a:hover{text-decoration-thickness:2px}
  .cap a:focus-visible{outline:2px solid var(--accent);outline-offset:2px;border-radius:3px}
  footer{margin-top:34px;color:var(--muted);font-size:12px;text-align:center;line-height:1.6}
  @media (max-width:640px){
    .kpis{grid-template-columns:repeat(2,1fr)}
    .checks{grid-template-columns:1fr}
    .banner .meta{margin-left:0;text-align:left}}
  /* Artifacts index — private dashboard only. */
  .agroup+.agroup{margin-top:20px}
  .agroup .gh{display:flex;align-items:baseline;gap:9px;margin:0 0 3px}
  .agroup .gh .gn{font-size:13.5px;font-weight:650}
  .agroup .gh .gc{font-size:11.5px;font-weight:600;color:var(--muted);
    font-variant-numeric:tabular-nums}
  .agroup .gb{font-size:12px;color:var(--muted);margin:0 0 11px}
  .alist{display:flex;flex-direction:column;gap:8px}
  a.arow{display:grid;grid-template-columns:1fr auto auto;gap:12px;align-items:center;
    text-decoration:none;color:inherit;background:var(--panel);border:1px solid var(--line);
    border-radius:11px;box-shadow:var(--shadow);padding:12px 15px;
    transition:border-color .12s ease,transform .12s ease}
  a.arow:hover{border-color:var(--accent);transform:translateY(-1px)}
  a.arow:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
  a.arow .at{font-size:13.5px;font-weight:600;letter-spacing:-.005em;
    overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  a.arow .atag{font-size:10px;font-weight:700;letter-spacing:.03em;text-transform:uppercase;
    color:var(--accent);background:color-mix(in srgb,var(--accent) 12%,transparent);
    border-radius:999px;padding:3px 9px;white-space:nowrap}
  a.arow .ao{font-size:12px;font-weight:650;color:var(--accent);white-space:nowrap}
  a.arow:hover .ao{text-decoration:underline}
  @media (prefers-reduced-motion:reduce){a.arow,a.arow:hover{transition:none}}
  @media (max-width:640px){a.arow{grid-template-columns:1fr auto}a.arow .ao{display:none}}
"""


# The raw frontmatter value is `stable`; the page's own legend calls that lifecycle
# stage "approved". Showing the raw value in drawers while the bars said "approved"
# read as a fourth, undocumented status — and made the visible library look as if
# nothing in it had ever been approved. One vocabulary, everywhere.
STATUS_LABEL = {"stable": "approved", "in-review": "in review", "draft": "draft"}


def status_label(status: str | None) -> str:
    return STATUS_LABEL.get(status or "", status or "")


def _status_pill(status: str | None) -> str:
    if not status:
        return ""
    cls = {"stable": "s-stable", "in-review": "s-review", "draft": "s-draft"}.get(status, "s-draft")
    return f'<span class="pill {cls}">{html.escape(status_label(status))}</span>'


def _card(label: str, count: int, inventory: dict, expandable: set[str]) -> str:
    esc = html.escape(label)
    gloss = html.escape(AREA_GLOSS.get(label, ""))
    if label in expandable and inventory.get(label):
        hint = '<span class="expand-hint"><span class="chev">›</span>Open list</span>'
        return (
            f'<button type="button" class="kpi-btn" data-area="{esc}" '
            f'aria-expanded="false" aria-controls="detail-drawer" aria-label="See all {count} {esc}">'
            f'<span class="n mono">{count}</span>'
            f'<span class="k">{esc}</span><span class="gloss">{gloss}</span>{hint}</button>'
        )
    # Withheld on the public page (their titles name product surfaces) rather
    # than simply non-expandable. Looking identical to a genuine count-only card
    # reads as a broken control; say so instead.
    withheld = (label in PRIVATE_EXPANDABLE and label not in expandable
                and inventory.get(label))
    note = ('<div class="withheld">Titles are on the internal dashboard</div>'
            if withheld else "")
    cls = "kpi inert" if withheld else "kpi"
    return (f'<div class="{cls}"><div class="n mono">{count}</div>'
            f'<div class="k">{esc}</div><div class="gloss">{gloss}</div>{note}</div>')


def _panel_src(label: str, inventory: dict, *, public: bool) -> str:
    """Hidden per-area list the drawer clones on open.

    Descriptions are private-only: a one-line summary can name a product surface,
    which the sanitized page must never carry. Public drawers stay titles-only.
    """
    entries = inventory[label]
    # A status badge repeated identically on every row carries no information and
    # buries the rows that do differ. When they are all the same, say it once in
    # the drawer header instead.
    statuses = {it.get("status") for it in entries}
    only = next(iter(statuses)) if len(statuses) == 1 else None
    uniform = bool(entries) and len(statuses) == 1 and only is not None
    if uniform:
        note = f'{len(entries)} · all {html.escape(status_label(only))}'
    elif entries and statuses == {None}:
        # Skills use the Claude-skill frontmatter shape, which has no status field.
        # Saying so beats a silently blank column the reader reads as missing data.
        note = f"{len(entries)} · no lifecycle status"
    else:
        note = str(len(entries))

    def row(it: dict) -> str:
        desc = "" if public or not it.get("desc") else (
            f'<span class="dsc">{html.escape(it["desc"])}</span>')
        pill = "" if uniform else _status_pill(it["status"])
        # Agent evidence base, private only. "runs" are scored benchmark results;
        # "sources" also counts doctrine files and dated incident records, so the
        # two numbers differing is the point — it shows how much of an agent's
        # knowledge rests on a measured run rather than a rule.
        ev = ""
        t = it.get("traps")
        if t is not None and not public:
            if not t["traps"]:
                ev = '<span class="ev none">no traps yet</span>'
            else:
                cls = "thin" if not t["runs"] else "ok"
                runs = (f'{t["runs"]} scored run{"s" if t["runs"] != 1 else ""}'
                        if t["runs"] else "no scored run")
                ev = (f'<span class="ev {cls}">{t["traps"]} traps · '
                      f'{t["sources"]} source{"s" if t["sources"] != 1 else ""} · '
                      f'{runs}</span>')
        return (f'<li><span class="nm">{html.escape(it["name"])}</span>'
                f'{pill}{desc}{ev}</li>')

    items = "".join(row(it) for it in entries)
    return (f'<div class="panel-src" data-area="{html.escape(label)}" '
            f'data-count="{note}" '
            f'data-gloss="{html.escape(AREA_GLOSS.get(label, ""))}" hidden>'
            f'<ul class="items">{items}</ul></div>')


def _series_path(points: list[float]) -> str:
    """SVG path for one normalised series (own min/max — shape, not scale)."""
    lo, hi = min(points), max(points)
    span = (hi - lo) or 1
    n = len(points)
    coords = [f"{round(100*i/(n-1),2)},{round(50-44*(v-lo)/span,2)}"
              for i, v in enumerate(points)]
    return "M" + "L".join(coords)


def _trend(history: list[dict]) -> str:
    """Labeled trend.

    An unlabeled up-and-right line reads as reassurance it has not earned — the
    2026-07-29 review's finding. Every series here prints its start value, end
    value and date range as text, so the picture cannot be misread on its own.
    Coverage joins automatically once two or more snapshots carry it.
    """
    if len(history) < 2:
        return ('<p class="cap" style="margin:0">This is the first daily snapshot. The trend — '
                'documents, approved share, and Storybook coverage over time — appears here once a '
                'few days accumulate, so you can watch whether the backlog is clearing.</p>')

    start, end = history[0].get("date", "?"), history[-1].get("date", "?")
    rows: list[str] = []

    def add(label: str, pts: list[float], fmt, cls: str, *, up_is_good: bool = True) -> None:
        if len(pts) < 2 or len(set(pts)) < 1:
            return
        # Say which way it moved, in words. A line that drifts down under a heading
        # called "Direction of travel" was previously left for the reader to notice.
        delta = pts[-1] - pts[0]
        # Only call a direction when the move is bigger than the rounding on the
        # printed values; a 29%->28% drift is one document, not a trend.
        if abs(delta) < 1:
            move, mcls = "flat", "flat"
        elif (delta > 0) == up_is_good:
            move, mcls = ("up" if delta > 0 else "down"), "good"
        else:
            move, mcls = ("up" if delta > 0 else "down"), "warn"
        rows.append(
            f'<div class="tr"><div class="tl"><span class="tk">{label}'
            f'<span class="mv {mcls}">{move}</span></span>'
            f'<span class="tv">{fmt(pts[0])} <span class="ar">&rarr;</span> '
            f'<b>{fmt(pts[-1])}</b></span></div>'
            f'<svg class="spark {cls}" role="img" aria-label="{html.escape(label)}: '
            f'{fmt(pts[0])} on {start} to {fmt(pts[-1])} on {end}" '
            f'viewBox="0 0 100 56" preserveAspectRatio="none">'
            f'<path d="{_series_path(pts)}"/></svg></div>')

    add("Documents", [float(h["areas"].get("Total docs", 0)) for h in history],
        lambda v: f"{int(v)}", "k-docs")

    shares = []
    for h in history:
        st = h.get("status") or {}
        tot = sum(st.values())
        shares.append(100 * st.get("stable", 0) / tot if tot else 0.0)
    add("Approved share", shares, lambda v: f"{v:.0f}%", "k-stable")

    cov_pts = [h["coverage"]["contracts_with_stories"] for h in history
               if isinstance(h.get("coverage"), dict)
               and "contracts_with_stories" in h["coverage"]]
    if len(cov_pts) >= 2:
        add("Spec'd components rendered in Storybook", [float(v) for v in cov_pts],
            lambda v: f"{int(v)}", "k-cov")
    else:
        rows.append('<p class="cap" style="margin:10px 0 0">Storybook coverage joins this '
                    'chart from tomorrow — today is its first recorded snapshot, so the '
                    'number to watch has no history here yet.</p>')

    return (f'<p class="cap" style="margin:0 0 12px">{start} &rarr; {end} '
            f'({len(history)} daily snapshots)</p>' + "".join(rows))


def _artifacts_section() -> str:
    """Rendered only on the private dashboard — the hand-maintained artifact index.

    Returns "" if the manifest is missing or empty so the section simply
    disappears rather than erroring. Never called for the public page.
    """
    if not ARTIFACTS_MANIFEST.is_file():
        return ""
    try:
        data = json.loads(ARTIFACTS_MANIFEST.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return ""
    # Drop the row that points at this very page — listing the dashboard as one of
    # its own deliverables is a dead end and reads as a bug.
    groups = []
    for g in data.get("groups", []):
        items = [it for it in g.get("items", [])
                 if "vault health" not in it.get("title", "").lower()]
        if items:
            groups.append({**g, "items": items})
    if not groups:
        return ""
    total = sum(len(g["items"]) for g in groups)

    blocks = []
    for g in groups:
        rows = "".join(
            f'<a class="arow" href="{html.escape(it["url"])}" target="_blank" rel="noopener">'
            f'<span class="at">{html.escape(it["title"])}</span>'
            f'<span class="atag">{html.escape(it.get("tag", ""))}</span>'
            f'<span class="ao">Open&nbsp;&rarr;</span></a>'
            for it in g["items"]
        )
        blocks.append(
            f'<div class="agroup"><div class="gh">'
            f'<span class="gn">{html.escape(g["name"])}</span>'
            f'<span class="gc">{len(g["items"])}</span></div>'
            f'<p class="gb">{html.escape(g.get("blurb", ""))}</p>'
            f'<div class="alist">{rows}</div></div>'
        )

    return (
        '<section>\n'
        '    <h2 class="s-head">Artifacts</h2>\n'
        f'    <p class="s-sub">The {total} things built from the vault so far. '
        '<b>Live</b> = a working tool the team uses; <b>Current</b> = an explainer that is '
        'up to date. In a browser these links open normally; inside a rendered Claude '
        'artifact they can’t navigate — use your gallery or the in-repo hub.</p>\n'
        f'    <div class="panel">{"".join(blocks)}</div>\n'
        '  </section>'
    )


def _component_library_section(today: date, cov: dict | None, *, public: bool) -> str:
    """Component-library build status + story coverage.

    Returns "" when the generated status file is missing, so the section simply
    disappears rather than erroring (same contract as _artifacts_section).

    Public/private difference: both pages link to the live Storybook; only the
    private dashboard links to the CI run, which is repo plumbing rather than
    something a stakeholder acts on. The Storybook URL contains a BLOCKLIST term,
    so it is carried by build_site.py's PUBLIC_URL_ALLOWLIST — an exact-URL
    exemption, not a relaxed blocklist (owner decision, 2026-07-29).
    """
    if not STORYBOOK_STATUS.is_file():
        return ""
    try:
        d = json.loads(STORYBOOK_STATUS.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return ""

    total = d.get("components") or 0
    storied = d.get("components_with_stories") or 0
    conclusion = d.get("conclusion")

    # A status fetched days ago is not evidence about today.
    fetched = d.get("fetched")
    stale = True
    if fetched:
        try:
            stale = (today - date.fromisoformat(fetched)).days > STORYBOOK_STALE_DAYS
        except ValueError:
            stale = True

    if conclusion is None:
        verdict, cls, detail = "Not built yet", "bad", "No CI run recorded on the default branch."
    elif stale:
        verdict, cls = "Unknown", "bad"
        detail = f"Last checked {html.escape(fetched or 'never')} — too old to report."
    elif conclusion == "success":
        verdict, cls = "Passing", "ok"
        detail = "Types, lint, the component tests and a full Storybook build."
    else:
        verdict, cls = "Failing", "bad"
        detail = f"Last run concluded {html.escape(str(conclusion))}."

    pct = round(storied / total * 100) if total else 0

    # Contracted-first target: the near-term goal is stories for the components we
    # have already written specs for. Green ONLY when that is complete — a 2%
    # figure must never render in the same success colour as "0 overdue", which is
    # exactly what the 2026-07-29 review caught.
    c_total = cov.get("contracts", 0) if cov else 0
    c_done = cov.get("contracts_with_stories", 0) if cov else 0
    c_pct = round(c_done / c_total * 100) if c_total else 0
    on_target = bool(c_total) and c_done == c_total
    cov_cls = "good" if on_target else "warn"
    goal = (f"Target met — next: the remaining {total - storied} in the library."
            if on_target else
            f"Target: stories for all {c_total} spec'd components ({c_done} done).")

    # The jargon gloss sits BELOW the numbers, not above them. Explaining
    # Storybook before showing the figure put ~120px of prose between a phone
    # user and the first fact on the page.
    gloss = ('<p class="cap" style="margin-top:14px"><b>Storybook</b> is the live, '
             'browsable library where each component is rendered in every state. A '
             'component that is not rendered there gets its spec written from source code '
             'alone, which is weaker. The build status only stops coverage slipping '
             'backwards.</p>')

    parts = []
    if d.get("site_url"):
        parts.append(f'<a href="{html.escape(d["site_url"])}" target="_blank" '
                     f'rel="noopener">Browse the component library &rarr;</a>')
    if not public:
        # CI run link and the contributor call to action are repo plumbing — useful
        # to the team, noise to a stakeholder.
        if d.get("run_url"):
            parts.append(f'<a href="{html.escape(d["run_url"])}" target="_blank" '
                         f'rel="noopener">See the latest build &rarr;</a>')
        parts.append("Every new story set moves this number — run the "
                     "<b>write-stories</b> skill.")
    links = ('<p class="cap" style="margin-top:14px">' + " · ".join(parts) + "</p>"
             if parts else "")

    return (
        '<section>\n'
        '    <h2 class="s-head">Component library</h2>\n'
        '    <p class="s-sub">How much of the component library is rendered in Storybook for '
        'specs to be written from. This is the number to watch.</p>\n'
        '    <div class="panel">\n'
        '      <div class="fresh">\n'
        f'        <div class="item {cov_cls}"><div class="n mono">{c_done}<span class="of">'
        f'/{c_total}</span></div>'
        f'<div><div class="k">Spec\'d components rendered in Storybook</div>'
        f'<div class="d">{c_pct}% &middot; {goal}</div></div></div>\n'
        f'        <div class="item"><div class="n mono">{storied}<span class="of">/{total}'
        f'</span></div>'
        f'<div><div class="k">Whole library rendered in Storybook</div>'
        f'<div class="d">{pct}% &middot; every component in the codebase, spec\'d or not'
        f'</div></div></div>\n'
        '      </div>\n'
        f'      <div class="checks" style="margin-top:16px"><div class="check {cls}">'
        f'<span class="mk">{"✓" if cls == "ok" else "!"}</span>'
        f'<span><span class="ct">Build: {verdict}</span>'
        f'<span class="cd">{detail}</span></span></div></div>\n'
        f'{gloss}{links}'
        '    </div>\n'
        '  </section>'
    )


def _shares(s: dict, total: int) -> dict[str, int]:
    """Percentages that sum to exactly 100 (largest remainder).

    Plain rounding gave 28+55+18 = 101%, which a numerate reader spots instantly
    and which undermines every other number on the page.
    """
    keys = ["stable", "in-review", "draft"]
    if not total:
        return {k: 0 for k in keys}
    exact = {k: 100 * s.get(k, 0) / total for k in keys}
    out = {k: int(v) for k, v in exact.items()}
    for k in sorted(keys, key=lambda k: exact[k] - int(exact[k]), reverse=True):
        if sum(out.values()) >= 100:
            break
        out[k] += 1
    return out


def render_body(scanned: dict, history: list[dict], healthy: bool,
                reasons: list[str] | None = None, *, public: bool) -> str:
    a = scanned["areas"]
    s = scanned["status"]
    inv = scanned["inventory"]
    total = scanned["status_total"] or 1
    expandable = PUBLIC_EXPANDABLE if public else PRIVATE_EXPANDABLE
    vcolor = "var(--stable)" if healthy else "var(--warn)"
    # Name the badge after what it actually measures. "Healthy" read as a verdict
    # on the whole vault, so a 1-of-12 coverage figure underneath it looked like a
    # contradiction the footnote had to apologise for. Scoping the label removes the
    # need to apologise.
    vtext = "All checks passing" if healthy else "Needs attention"
    reasons = reasons or []

    cards = "".join(_card(label, a[label], inv, expandable) for label in CARD_ORDER)
    panel_srcs = "".join(
        _panel_src(label, inv, public=public) for label in CARD_ORDER
        if label in expandable and inv.get(label)
    )

    shares = _shares(s, total)

    def bar(key: str, name: str) -> str:
        # Meaning folded into the row label — the separate legend duplicated the
        # labels sitting directly beneath it.
        pct = shares[key]
        color = {"stable": "var(--stable)", "in-review": "var(--review)",
                 "draft": "var(--draft)"}[key]
        return (f'<div class="row"><span class="name">{name}'
                f'<span class="nm">{STATUS_MEANING[key]}</span></span>'
                f'<span class="track"><span class="fill" style="width:{pct}%;background:{color}"></span></span>'
                f'<span class="val"><b>{s[key]}</b> · {pct}%</span></div>')

    checks = "".join(
        f'<div class="check {"ok" if ok else "bad"}"><span class="mk">{"✓" if ok else "✕"}</span>'
        f'<span><span class="ct">{html.escape(CHECK_LABELS.get(name, (name, ""))[0])}</span>'
        f'<span class="cd">{html.escape(CHECK_LABELS.get(name, (name, ""))[1])}</span></span></div>'
        for name, ok in scanned["integrity"].items()
    )
    n_fail = sum(1 for ok in scanned["integrity"].values() if not ok)

    # The hero summary is built from the SAME reasons list the verdict is computed
    # from. Previously the summary only knew about checks and overdue counts, so a
    # backlog-drift day rendered "Needs attention" directly above "all checks
    # passing · nothing overdue" — the page contradicting itself.
    cov = story_coverage(inv)
    if healthy:
        # The badge itself now says "All checks passing", so the summary adds the
        # facts it does NOT cover rather than repeating it.
        summary = " · ".join([
            f"{a['Total docs']} documents",
            "nothing overdue",
            "no backlog growth",
        ] + ([f"Storybook coverage {cov['contracts_with_stories']}/{cov['contracts']}"]
             if cov else []))
    else:
        summary = " · ".join(reasons) if reasons else "see the internal report"

    stale_good = "good" if not scanned["stale"] else "bad"
    mal_good = "good" if not scanned["malformed"] else "bad"

    # Private only: entries quote corrections and product-surface names verbatim,
    # so this tile never renders on the sanitised page (same rule as the artifact
    # index). An untriaged queue is a warning, not a failure — the vault is still
    # correct, it just hasn't absorbed a correction yet.
    # Traps are the agents' accumulated failure knowledge. Reporting the count
    # alone would read as "done"; what matters is the evidence under it, so this
    # says how much recorded material has not yet been mined. Private only — it
    # names internal process, and a stakeholder has no action to take on it.
    tr = scanned.get("traps") or {}
    traps_note = ""
    if tr.get("traps") and not public:
        per = agent_traps()
        thin = sorted(n for n, d in per.items() if d["traps"] and not d["runs"])
        named = (f" Resting on no scored run yet: "
                 + ", ".join(f"<b>{html.escape(n)}</b>" for n in thin) + "."
                 if thin else " Every agent with traps cites at least one scored run.")
        unmined = tr.get("unmined", 0)
        gap = (f" <b>{unmined}</b> of <b>{tr['results']}</b> recorded benchmark results have "
               f"not yet produced a trap — unmined evidence, not a defect."
               if unmined else " Every recorded benchmark result has been mined.")
        traps_note = (
            f'<p class="cap" style="margin-top:14px"><b>{tr["traps"]}</b> agent traps — '
            f'recorded failure modes stated inline on the agent that makes them — across '
            f'<b>{tr["with_traps"]}</b> of <b>{tr["agents"]}</b> agents. They are only as good '
            f'as the evidence beneath them.{named}{gap} Open an agent above to see its base; '
            f'each carries an <b>Evidence base</b> section saying what would strengthen it.</p>')

    lessons = scanned.get("lessons") or []
    lessons_tile = ""
    if not public:
        oldest = lessons[0].split("(")[-1].rstrip(")") if lessons else ""
        detail = (f"Captured corrections not yet applied — oldest {oldest}"
                  if lessons else "Every captured correction has landed")
        lessons_tile = (
            f'<div class="item {"warn" if lessons else "good"}">'
            f'<div class="n mono">{len(lessons)}</div>'
            f'<div><div class="k">Open lessons</div>'
            f'<div class="d">{html.escape(detail)}</div></div></div>')
    trend = _trend(history)
    reveal = ("Agents, Skills, Components and Patterns"
              if public else "Every card")
    owner = (f"Owner: {OWNER_NAME} · {OWNER_ROLE}" if not public
             else f"Maintained by the {OWNER_ROLE} owner")
    # The redaction promise describes the sanitised build. On the internal
    # dashboard it was simply untrue — that page does show paths and names.
    footer_note = ("Sanitized aggregate health of the shared Orbit Design Brain vault. "
                   "Counts and maturity only — never internal file paths."
                   if public else
                   "Internal view of the shared Orbit Design Brain vault. "
                   "The stakeholder page carries counts and maturity only.")
    # Artifact index is private-only: several titles name product surfaces, so it
    # never renders on the public/sanitized page (consistent with hiding platform profiles).
    artifacts = "" if public else _artifacts_section()
    # Rendered on both pages, but the private one carries the links (see the
    # function's docstring for why the public page withholds the URL).
    component_library = _component_library_section(
        date.fromisoformat(scanned["date"]), cov, public=public)

    # One sentence that reconciles every denominator on the page. Four numbers
    # (documents / with-status / library / spec'd) previously appeared in four
    # different sections with no explanation of how they relate.
    rest = scanned.get("rest") or {}
    parts = [f"<b>{n}</b> {label}" for label, n in (rest.get("buckets") or {}).items() if n]
    if rest.get("other"):
        parts.append(f"<b>{rest['other']}</b> indexes, templates and generated files")
    remainder = ""
    if parts:
        listed = rest.get("listed", 0)
        phrase = parts[0] if len(parts) == 1 else ", ".join(parts[:-1]) + f", and {parts[-1]}"
        remainder = (f" The six cards below list <b>{listed}</b> of them — the reusable "
                     f"building blocks. The other "
                     f"<b>{a['Total docs'] - listed}</b> are {phrase}.")
    denominators = (
        f"<b>{a['Total docs']}</b> documents in the vault; <b>{scanned['status_total']}</b> "
        f"carry a lifecycle status."
        + remainder
        + " The component library is a separate codebase, counted separately: "
        + (f"<b>{cov['components']}</b> components, <b>{cov['contracts']}</b> of which have "
           f"a written spec here ({round(100 * cov['contracts'] / cov['components']) if cov['components'] else 0}%), "
           f"and <b>{cov['contracts_with_stories']}</b> rendered in Storybook. Specs for the remaining "
           f"<b>{cov['components'] - cov['contracts']}</b> are the work after that."
           if cov else "counts appear once the component feed reports.")
    )

    return f"""<div id="shell"><div class="wrap">
  <header>
    <div class="eyebrow">Orbit Design Brain</div>
    <h1>Vault Health</h1>
    <p class="purpose">The Orbit Design Brain is the living specification our products are
      built to — the written rules, component specs and worked examples that both people
      and AI tools follow. This page is its health check.</p>
    <div class="banner" style="--verdict:{vcolor}">
      <span class="dot"></span>
      <div>
        <div class="verdict">{vtext}</div>
        <div class="summary-line">{summary}</div>
      </div>
      <span class="meta">Updated {scanned['date']}<br>Refreshes daily</span>
    </div>
    <details class="explain">
      <summary>How to read these numbers</summary>
      <p class="verdict-def">This badge covers three things only: the automated checks pass,
        nothing is overdue for review, and the review backlog isn’t growing. It is not a
        verdict on the vault as a whole — Storybook coverage and how much is still in review
        are separate measures, reported below.</p>
      <p class="denoms">{denominators}</p>
    </details>
  </header>

  {component_library}

  <section>
    <h2 class="s-head">Checks &amp; attention</h2>
    <p class="s-sub">The ticks run automatically on every change and are pass/fail. The
      counters beneath them track things that have drifted out of good standing — nothing
      here is broken, but a non-zero count is work someone owes the vault.</p>
    <div class="panel">
      <div class="checks">{checks}</div>
      <div class="fresh" style="margin-top:16px">
        <div class="item {stale_good}"><div class="n mono">{len(scanned['stale'])}</div>
          <div><div class="k">Overdue for review</div><div class="d">Not looked at in {STALE_AFTER_DAYS}+ days</div></div></div>
        <div class="item {mal_good}"><div class="n mono">{len(scanned['malformed'])}</div>
          <div><div class="k">Metadata problems</div><div class="d">Missing or invalid tags/dates</div></div></div>
        {lessons_tile}
      </div>
    </div>
  </section>

  <section>
    <h2 class="s-head">How ready it is</h2>
    <p class="s-sub">Where the {scanned['status_total']} documents that carry a lifecycle
      status (draft → in review → approved) sit today. The vault is still being built, so
      most documents have not reached approved yet; the target is to move the in-review
      column down over time.</p>
    <div class="panel">
      {bar('stable','Approved')}{bar('in-review','In review')}{bar('draft','Draft')}
    </div>
  </section>

  <section>
    <h2 class="s-head">What's inside</h2>
    <p class="s-sub">The building blocks the vault holds. {reveal} can be opened to list what's in them.</p>
    <div class="kpis">{cards}</div>
    {traps_note}
  </section>
  <div hidden>{panel_srcs}</div>

  <section>
    <h2 class="s-head">Trend</h2>
    <p class="s-sub">Direction of travel since daily snapshots began. Each line shows its
      start value, its end value, and which way it moved.</p>
    <div class="panel">{trend}</div>
  </section>

  {artifacts}

  <footer>{owner}<br>{footer_note}</footer>
</div></div>

<aside class="drawer" id="detail-drawer" role="region" aria-labelledby="drawer-title" aria-hidden="true">
  <div class="dhead">
    <h3 id="drawer-title"></h3>
    <span class="dcount"></span>
    <button type="button" class="drawer-close" aria-label="Close panel">&times;</button>
  </div>
  <p class="dgloss"></p>
  <div class="drawer-body"></div>
</aside>

<script>
(function(){{
  var body=document.body,
      drawer=document.querySelector('.drawer'),
      title=drawer.querySelector('#drawer-title'),
      count=drawer.querySelector('.dcount'),
      gloss=drawer.querySelector('.dgloss'),
      dbody=drawer.querySelector('.drawer-body'),
      closeBtn=drawer.querySelector('.drawer-close'),
      last=null;
  function open(area){{
    var src=document.querySelector('.panel-src[data-area="'+area+'"]');
    if(!src) return;
    title.textContent=area;
    count.textContent=src.getAttribute('data-count');
    gloss.textContent=src.getAttribute('data-gloss')||'';
    dbody.innerHTML='';
    dbody.appendChild(src.querySelector('.items').cloneNode(true));
    body.classList.add('drawer-open');
    drawer.setAttribute('aria-hidden','false');
    document.querySelectorAll('.kpi-btn').forEach(function(x){{x.setAttribute('aria-expanded', x===last?'true':'false');}});
    closeBtn.focus();
  }}
  function close(){{
    body.classList.remove('drawer-open');
    drawer.setAttribute('aria-hidden','true');
    document.querySelectorAll('.kpi-btn').forEach(function(x){{x.setAttribute('aria-expanded','false');}});
    if(last) last.focus();
  }}
  document.querySelectorAll('.kpi-btn').forEach(function(btn){{
    btn.addEventListener('click',function(){{
      if(body.classList.contains('drawer-open')&&last===btn){{ close(); return; }}
      last=btn; open(btn.getAttribute('data-area'));
    }});
  }});
  closeBtn.addEventListener('click',close);
  document.addEventListener('keydown',function(e){{
    if(e.key==='Escape'&&body.classList.contains('drawer-open')) close();
  }});
}})();
</script>"""


def render_standalone(scanned: dict, history: list[dict], healthy: bool,
                      reasons: list[str] | None = None) -> str:
    body = render_body(scanned, history, healthy, reasons, public=True)
    # No hardcoded data-theme: let the viewer's OS preference drive the page
    # (prefers-color-scheme). The :root[data-theme=…] overrides still win if a
    # host stamps the attribute.
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Orbit Design Brain — Vault Health</title>
<style>{STYLE}</style>
</head>
<body>
{body}
</body>
</html>
"""


def render_artifact(scanned: dict, history: list[dict], healthy: bool,
                    reasons: list[str] | None = None) -> str:
    """Body-only (full drill-down) for the private Claude Artifact."""
    body = render_body(scanned, history, healthy, reasons, public=False)
    return (f"<title>Orbit Design Brain — Vault Health</title>\n"
            f"<style>{STYLE}</style>\n{body}\n")


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true",
                        help="emit the verdict + metrics as JSON (for CI alerting)")
    parser.add_argument("--artifact-out", metavar="PATH",
                        help="also write a body-only full-detail HTML for the private Artifact")
    args = parser.parse_args()

    today = date.today()
    scanned = scan(today)
    history, previous = update_history(scanned)
    healthy, reasons = verdict(scanned, previous)

    HEALTH_MD.write_text(render_md(scanned, previous, healthy, reasons), encoding="utf-8")
    HEALTH_HTML.write_text(render_standalone(scanned, history, healthy, reasons), encoding="utf-8")
    if args.artifact_out:
        Path(args.artifact_out).write_text(
            render_artifact(scanned, history, healthy, reasons), encoding="utf-8")

    if args.json:
        print(json.dumps({
            "date": scanned["date"],
            "healthy": healthy,
            "reasons": reasons,
            "areas": scanned["areas"],
            "status": scanned["status"],
        }, indent=2))
    else:
        print(f"Vault health {scanned['date']}: {'HEALTHY' if healthy else 'DRIFT'}")
        for r in reasons:
            print(f"  - {r}")
        out = [HEALTH_MD.name, HEALTH_HTML.name, HISTORY_PATH.name]
        if args.artifact_out:
            out.append(args.artifact_out)
        print("Wrote " + ", ".join(out))


if __name__ == "__main__":
    main()
